### ISSUE TITLE
Dead Links in Docs

### ISSUE THREAD

**Issue by caseyturnerarrington** [onflow/flow#101]
I noticed the following link issues when going through the docs:

https://flow-docs-git-token.onflow.vercel.app/token/earn/# > All links within this page do not go anywhere. These should be:
- [x] The 'Alpha Program', use this: https://www.onflow.org/flow-alpha
- [x] The 'Token Lease Staking Program', use this: https://www.onflow.org/node-validators
- [x] Remove Open World Builders link altogether.

https://flow-docs-git-mackenzie-deploy-fixes.onflow.vercel.app/intro/flow-token/# > The same 3 links as the above comment are on this page and also do not go anywhere. 
- [x] Please cascade these changes here as well.

**Others:**
- https://flow-docs-git-token.onflow.vercel.app/token/staking/node-operators/ > Link 'submit a staking request without tokens' goes to a dead page.
- https://flow-docs-git-token.onflow.vercel.app/token/staking/node-operators/ > Link 'enable delegation for your node' goes to a dead page
- https://flow-docs-git-token.onflow.vercel.app/token/staking/node-operators/ > Link 'unbonded / withdrawn' goes to a dead page
- https://flow-docs-git-token.onflow.vercel.app/token/staking/node-operators/ > Link 'withdraw these tokens at anytime' goes to a dead page
- https://flow-docs-git-token.onflow.vercel.app/token/staking/node-operators/ > Link 're-stake them' goes to a dead page

**Comment by caseyturnerarrington** [comment]
Closed via PR https://github.com/onflow/flow/pull/116

**Comment by 10thfloor** [comment]
Closed because this content has moved to other docs. Willmake sure there are no dead links in those PRs.
