### ISSUE TITLE
Fix wrong link pointing towards non-fungible-tokens

### ISSUE THREAD

**Issue by wise4rmgod** [onflow/flow#1054]
https://docs.onflow.org/cadence/tutorial/04-non-fungible-tokens/

**Comment by wise4rmgod** [comment]
To reproduce this error, go to this link https://docs.onflow.org/, click the tutorial dropdown, and click `Create Non-fungible-tokens (NFT)`

**Comment by alxflw** [comment]
correct link: https://docs.onflow.org/cadence/tutorial/05-non-fungible-tokens-1/
