### ISSUE TITLE
Docs: Security Best Practices for Cadence

### ISSUE THREAD

**Issue by alxflw** [onflow/flow#1063]
Take content from https://github.com/HalbornSecurity/Security-Best-Practices-for-Cadence-Developers-Flow-

and merge it into the Cadence section (https://docs.onflow.org/cadence/), likely best as a new page

**Comment by bluesign** [comment]
I think this is too brief ( not diving in to detail ), in my opinion it can have very bad influence on developers. We already have low composability, this suggestions will kill it a bit more.

**Comment by alxflw** [comment]
@franklywatson it seems the content here needs more discussion. @wise4rmgod could help get it onto the docs page but let's make sure we iterate on the content. can you please response to @bluesign feedback?

**Comment by alxflw** [comment]
hey @bluesign - we've discussed your feedback and decided to get a first version of this onto the docs right away + iterate on it later. this content is adding value and given our limited resources to improve it right now, we will have to address some points either later. if you have the ability to improve it based on your suggestions, a PR would be very welcome. thanks!
