### ISSUE TITLE
Use of undeclared tag in MDX results in div element

### ISSUE THREAD

**Issue by turbolent** [onflow/flow#112]
## Instructions

Use a tag that's not declared in an MDX, for example `Img`, and don't import it.

### Problem

Instead of erroring, a div element is produced.

For example `<Img src="foo" />` results in a non-sensical `<div src="foo"></div>`

### Steps to Reproduce 

See above

### Acceptance Criteria

The build process should error and abort, instead of silently accepting the invalid tag.

**Comment by 10thfloor** [comment]
@turbolent I think this is the expected behaviour? 
https://mdxjs.com/playground

**Comment by turbolent** [comment]
Oh wow, you're right. Using an undefined component results in a runtime error! 🤦 
It just returns a `div` element and adds a `console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope")` ...

**Comment by turbolent** [comment]
I wish this was an error – we run the build and so even when we use an undefined component, the build will just pass. Nobody ever looks at the warnings of a successful build
