### ISSUE TITLE
access node in doc dose not work 

### ISSUE THREAD

**Issue by Bha91** [onflow/flow#1146]
Hi 
the access node (access.mainnet.nodes.onflow.org:9000) in this doc does not work.
https://github.com/onflow/flow/blob/master/docs/content/nodes/access-api.mdx#current-mainnet
I have tested it with 
`curl --location --request GET 'access.mainnet.nodes.onflow.org:9000/blocks/?height=final'`

**Comment by bluesign** [comment]
port 9000 is GRPC endpoint. 

for REST API, you should use: https://rest-mainnet.onflow.org

`curl "https://rest-mainnet.onflow.org/v1/blocks?height=final"`
