### ISSUE TITLE
Include Flow Access API rate limits for REST API

### ISSUE THREAD

**Issue by ph0ph0** [onflow/flow#1152]
## Introduction

We currently have a page that details the rate limits for Dapper Labs access nodes via the gRPC API.

However, iirc the REST API is the recommended API to use, but the rate limits are not provided.

Knowing rate limits is critical for building scalable architectures, and so this information should be readily available.

## Suggestion

If the rate limits for the REST API are the same as for the gRPC API, then a note should be included on the page clearly stating this.

If the rate limits are different, then a new page should be included that provides these values.

**Comment by ph0ph0** [comment]
For reference, here is the page that states the gRPC rates:

https://developers.flow.com/nodes/access-api-rate-limits

**Comment by bluesign** [comment]
According to response headers, it is 10 requests per second for each endpoint.

**Comment by ph0ph0** [comment]
Thanks for checking @bluesign!

Ok so the REST API rate limits are 200 times smaller than the gRPC endpoints... 

And is that per client IP as well @bluesign?

That means the rate limits on the REST API are incredibly tight and shouldn't be used for admin backends, where calling scripts to populate user objects etc will very quickly consume this.

This is really important information that should be documented in the docs... It should also be linked anywhere the REST API is suggested/recommended (if it is in the docs somewhere?) so that people don't use the REST API for anything in production...

**Comment by bluesign** [comment]
yeah for sure per IP. It can be some misconfiguration also. ( they are pretty low )

**Comment by ph0ph0** [comment]
@bluesign ok cool thanks for confirming. Who is the best person to raise this with as I feel as though 10 requests per second on the REST API is not suitable for production, so if it is a misconfiguration, then it should be addressed?

**Comment by vishalchangrani** [comment]
> @bluesign ok cool thanks for confirming. Who is the best person to raise this with/tag as I feel as though 10 requests per second on the REST API is not suitable for production, so if it is a misconfiguration, then it should be addressed?

So - I have put this [PR](https://github.com/onflow/flow/pull/1167) to fix the documentation. The REST limits were set to 10 initially when we were launching the API for the first time but you are right, they can now be raised.

**Comment by vishalchangrani** [comment]
The [docs](https://developers.flow.com/nodes/access-api-rate-limits) have been updated

**Comment by ph0ph0** [comment]
Thank you for updating @vishalchangrani, appreciate it! 

I have read your doc changes at the bottom of the page and they state that the REST limits are set to 40. You indicated in your comment above that the REST limits would now be raised, so was wondering when they will be raised, and what is the likely value they will be raised to?

Thanks!

**Comment by franklywatson** [comment]
@ph0ph0 may i ask what use case you have that needs the higher rates? Thanks

**Comment by bluesign** [comment]
To make it clear, REST limits were not 40, they were 10. ( Not that makes a much difference ) but  maybe you have different limits for AN and load balancer, better to check
