### ISSUE TITLE
Imposible to generate node-machine-account-info.priv.json file on consensus node. OR machine account address (...) is not valid for any chain

### ISSUE THREAD

**Issue by minzak** [onflow/flow#1162]
I want to bootstrap a new consensus node, where need Machine Account.
I use 2 manuals:
https://github.com/onflow/flow/blob/master/docs/content/node-operation/node-bootstrap.mdx
https://github.com/onflow/flow/blob/master/docs/content/node-operation/machine-existing-operator.mdx

Also link https://github.com/onflow/flow/blob/master/flow-port/staking-guide/#existing-node-operators - is not working = 404 Error.

In 1st step, I must run `bootstrap key` command, ad I have the output:
```root@flow1 /var/flow # tree 
.
└── bootstrap
    ├── private-root-information
    │   └── private-node-info_e31c15c38d9f94fbf7851e89c49ac03413969125accb47e35fbe2d0fbcd73c2a
    │       ├── node-info.priv.json
    │       ├── node-machine-account-key.priv.json
    │       └── secretsdb-key
    └── public-root-information
        ├── node-id
        └── node-info.pub.e31c15c38d9f94fbf7851e89c49ac03413969125accb47e35fbe2d0fbcd73c2a.json
```        
In 2nd step, I must use `bootstrap machine-account`
But I use a lot of variants and no one not worked

```
bootstrap machine-account --address <mydomain>.org:3569 -o /var/flow/bootstrap
<nil> ERR invalid machine account address input error="machine account address (0000000000000095) is not valid for any chain"
```

```
bootstrap machine-account --address <mydomain>.org -o /var/flow/bootstrap
<nil> ERR invalid machine account address input error="machine account address (0000000000000009) is not valid for any chain"
```
Also here is the wrong, not worked command - https://github.com/onflow/flow/blob/master/docs/content/node-operation/node-bootstrap.mdx#finalize-machine-account-setup
```
bootstrap key --address <MYDOMAIN>:3569 --role consensus  -o /var/flow/bootstrap > result.txt
YOUR_MACHINE_ACCOUNT_ADDRESS=$(echo $(cat result.txt |sed 's/\x1b\[[0-9;]*[mGKHF]//g' | grep machineAccountPubKey | cut -d '=' -f2) )
echo ${YOUR_MACHINE_ACCOUNT_ADDRESS}
bootstrap machine-account --address ${YOUR_MACHINE_ACCOUNT_ADDRESS} -o /var/flow/bootstrap

f847b840dac73c6ea71f36668648b22b27835ac1125698b6b3da9e035006bb89a08636f6c3ef63848e29637ba8e8a06cad3b9367d244ac5e26575d21babb7a1c08686b6202038203e8
<nil> ERR invalid machine account address input error="machine account address (686b6202038203e8) is not valid for any chain"
```

How to get `node-machine-account-info.priv.json` file, what is wrong?
Thanks.

**Comment by minzak** [comment]
At this moment I have 2 solutions:
1st:
```
bootstrap key --address 95.xx.xx.xx:3569 --role consensus  -o /var/flow/bootstrap > result1.txt
bootstrap machine-account --address 0x3axxxxxxxxxxd813 -o /var/flow/bootstrap > result2.txt
```
where address - it is the **wallet address** from `port.onflow.org` it is also can seen in URL `https://port.onflow.org/account/0x3axxxxxxxxxxd813`

But NOWHERE about this, and this is correct?

2th:
```
bootstrap genconfig --access 0 --collection 0 --consensus 1 --execution 0 --verification 0 --address-format "%s.flow%1d.<MYDOMAIN>:3569"
bootstrap keygen --config bootstrap --root-chain main -o .bootstrap
...
```
And need add some files like `node-id` maybe change format in some files

**Comment by vishalchangrani** [comment]
Hi @minzak ,
For new consensus and collection node operator the machine account should be created when you stake the node on Flow port. [Here](https://developers.flow.com/nodes/staking/machine-account) is a description of the machine account and how it gets created. However, note that at this point we are working on instituting a new framework to onboard new nodes and have temporarily stopped adding Consensus nodes.

**Comment by minzak** [comment]
Thanks.
