### ISSUE TITLE
Google Bucket Missing Block Cbor file

### ISSUE THREAD

**Issue by skyonedot** [onflow/flow#1170]
### Problem

The Cbor file storage in google cloud bucket is missing, the missing number is a lot.

For example 

- From Block 40252691 to 40314354, all the cbor is missing
  - BlockID : cfa2fcc28aeb773f4534f5c4957d60e3fb0b14d01b06445a0fa48508871c1936
  - https://storage.googleapis.com/flow_public_mainnet20_execution_state/cfa2fcc28aeb773f4534f5c4957d60e3fb0b14d01b06445a0fa48508871c1936.cbor
  - BlockID: ce4988f0fa7a65ed98380f2d0da58416cc7b4bf942888856c8e71a9617d42fa4
  - https://storage.googleapis.com/flow_public_mainnet20_execution_state/ce4988f0fa7a65ed98380f2d0da58416cc7b4bf942888856c8e71a9617d42fa4.cbor

I just take one day block as example, please check it.

**Comment by m4ksio** [comment]
Thank for the report! We are aware of the issue and fix is in progress

**Comment by m4ksio** [comment]
All past blocks for mainnet20 are uploaded now, they should also be uploaded continuously.
Note, that there was a slight change in CBOR-encoded data structure, please use `v0.28.11` tag (or higher) from flow-go to decode the data correctly.

**Comment by bluesign** [comment]
@m4ksio We still don't have any chance to listen to those via network, right?

**Comment by franklywatson** [comment]
@bluesign we will be deprecating the use of GCP in the execution state sync before the end of 2022. The sync is based on bitswap and is tested and deployed on mainnet. It's just not being exercised at this time.
