### ISSUE TITLE
Access to API Spec Documentation needs to the added to Flow Docs

### ISSUE THREAD

**Issue by kzucky** [onflow/flow#126]
### Problem

Node Operators need to query the access API to get events for a block range. 
Unfortunately, the documentation for that seems to have been lost and is an important place to go for anyone using our APIs

### Steps to Reproduce 

one older one here - 
[](https://github.com/onflow/flow/blob/protoc-gen-js/docs/access-api-spec.md#geteventsforblockids)
Needs to put/accessible on the Flow Docs site

### Acceptance Criteria

<if any>
  
Blockchain Coalition reached out over Discord with the following:

_"Hey @rrrkren, thanks, works good for live data! However I have a question about archive transactions (for the latest node I assume) we cant find mint events for the following moments 525289 - 525363, I assume they should have been minted somewhere between 7673291 and 7673293 block numbers, can you try to find a transaction id of a mint so that I can confirm that?"_

Additional context: Sent older link and the following:
"so if they were to query for events between that range - 7673291 and 7673293 they should find all the events"

cc @vishalchangrani for more context.

**Comment by rrrkren** [comment]
the transaction for those moments (`74ccbde9b23524301ecfaee2515b7da705707ed8598527eeb86e1c4582ae2a14`), and the `A.0b2a3299cc857e29.TopShot.MomentMinted` events are still accessible in the current `mainnet1` and not archived. the transaction was executed when we had flow turbulence last week and that's likely why they had issues. I've checked the event polling myself and it works. For some context Cryptoslam uses C# and the flow proto rpc directly here:  https://github.com/onflow/flow/blob/master/protobuf/flow/access/access.proto#L76

**Comment by rrrkren** [comment]
@kzucky flow-js-sdk currently actually doesn't support `GetEventsForHeightRange`, the link you sent them is actually `GetEventsForBlockIDs` which doesn't work for their particular use case.

**Comment by rrrkren** [comment]
I do however agree that we should have documentation on the proto rpcs so people who want to generate stubs in their own language that we don't support can do so with better support.

**Comment by 10thfloor** [comment]
Added here: 
https://docs.onflow.org/protocol/access-api/

**Comment by vishalchangrani** [comment]
The documentation is now here - https://github.com/onflow/flow/blob/master/docs/content/core-contracts/access-api.md

**Comment by vishalchangrani** [comment]
Closing this issue since the documentation is now available.

**Comment by NathanMaton** [comment]
The latest link from January goes to a 404.

**Comment by vishalchangrani** [comment]
> The latest link from January goes to a 404.

https://docs.onflow.org/access-api
