### ISSUE TITLE
Fix Links on Flow Token page 

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#177]
### Problem

Links on https://docs.onflow.org/token are currently 404ing

### Steps to Reproduce 

Go to https://docs.onflow.org/token and click on links 

### Acceptance Criteria

All links are properly linked on the page

**Comment by 10thfloor** [comment]
The links are working now, but there is still some weirdness, specifically when you click on any of the links here
![Screen Shot 2020-12-01 at 4 06 35 PM](https://user-images.githubusercontent.com/901466/100811309-32f43e80-33ef-11eb-8469-e44a820f88a1.png)
@timmymmit @joshuahannan Any idea what's going on here?

**Comment by 10thfloor** [comment]
Closed by 4869f1a
Broken link from "Earn Flow as a Validator" now points to 'staking/technical-overview`
