### ISSUE TITLE
Documentation: Update Accessing Emulator Document

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#191]
## Context

We need to update the current Emulator to provide additional context about what Emulator is as well as associated warning and risk of being on Emulator

## Definition of Done

Migrate existing Emulator document updated with the following:

-[] Explain what Emulator is exactly
-[] possible state changes and sporks
-[] Encouraged use for testing
-[] Disclaimers and warnings about network

## PR Review

Who is your Code Partner - @10thfloor 
Who can provide external eyes - @robmyers @timmymmit @joshuahannan @turbolent @10thfloor

**Comment by 10thfloor** [comment]
@psiemens started?

**Comment by psiemens** [comment]
@10thfloor Just starting now actually!
