### ISSUE TITLE
Documentation: Storage Fees Writeup

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#194]
## Context

Storage fees are being added to the protocol and we need to let people know what it is and how they will be affected by it.

## Definition of Done

Provide an overview of storage fees and what they are, how much they are, what scenarios they are applied and what developers should be aware of when working with the fees.

## PR Review 

Who is your Code Partner - @turbolent 
Who can provide external eyes - @timmymmit @psiemens @10thfloor

**Comment by janezpodhostnik** [comment]
Draft in progress here: https://www.notion.so/dapperlabs/Flow-Storage-0c08e9e5156b4eadb839e5baaabe7f5f

**Comment by 10thfloor** [comment]
Closed by #311
