### ISSUE TITLE
Update Staking and Node Operation Docs with Edits and make sections public

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#204]
## Context

Recently we sent over our Staking and Node Operation docs to Natasha to edit. She has provided edits that we want to update our docs to use. Once we put up her edits we can then make these sections public on the Doc Site.

## Definition of Done

The edits found here are updated on the docsite:
-[] https://docs.google.com/document/d/1HeE0zgojQ1R4OrvxC4L-qw9CROeu1h8hl0tVCUFBHmg/edit
-[] https://docs.google.com/document/d/1pntHLOxMKnhe7oCfFo1OvaIYTVUPQOM27RxH9js0J9c/edit#heading=h.wru0zdcvvvj6

Node Operation and Staking sections are public. 

## PR Review 

Who is your Code Partner - @psiemens 
Who can provide external eyes - @timmymmit @joshuahannan @robmyers @psiemens

**Comment by joshuahannan** [comment]
Would we be able to ask her to make her edits more obvious? Currently we'll have to manually compare each document line-by-line, which will be a very time-consuming process.
