### ISSUE TITLE
Terms of Flow Lease

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#243]
## Context

People want to know what they need to do to keep their Flow Lease. We need to put it in writing so people can refer to it.

## Definition of Done

Terms of Flow Lease up on DocSite

## PR Review 

Who is your Code Partner - @laynelafrance 
Who can provide external eyes - @psiemens @joshuahannan @timmymmit 

## Internal Testing 
Estimation of core issue should capture larger testing efforts

**Comment by joshuahannan** [comment]
Should we really be putting all this specific information about leases on the docs site? The leases are special relationships that we form with node operators that we have spoken to individually. Doesn't really seem like something that should be public

**Comment by 10thfloor** [comment]
@caseyturnerarrington Can we close this?

**Comment by caseyturnerarrington** [comment]
Yeah we can close this.
