### ISSUE TITLE
Query the validators for each block

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#290]
### Issue To Be Solved

Network observers wish to view the list of nodes that have signed each block returned by the Access API. However, the API does not currently return this information. 

> currently there is no way to figure out which nodes have signed a block as the signature in a block is a concatenated BLS signature, isn't it?

### Context

This feature has been requested by teams implementing block explorers for Flow.

**Comment by laynelafrance** [comment]
Features Missing:
- Transaction link (look up by hash)
- Etherscan basics

**Comment by caseyturnerarrington** [comment]
View a list of consensus nodes that have signed the block. This info is on the block header.
