### ISSUE TITLE
URLs showing #gatsby-focus-wrapper in links

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow#301]
## Context

Whenever someone clicks on a search result the page link seems to be adding #gatsby-focus-wrapper

## Definition of Done

#gatsby-focus-wrapper is not added to links from search results

## PR Review 

Who is your Code Partner - @psiemens 
Who can provide external eyes - @timmymmit @githubwei

**Comment by 10thfloor** [comment]
Turns out this is done for accessibility purposes. 
See here: https://reach.tech/router/accessibility
We want accessibility, so I think we'll keep this.

**Comment by psiemens** [comment]
Hmm, how is this an accessibility feature? I can't find any elements with ID `gatsby-focus-wrapper` in the DOM
