### ISSUE TITLE
FAQ updates (Sprint 32)

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#331]
## Context

We need to update the FAQ page with new questions that have surfaced in the past month.

## Definition of Done

* The FAQ page(s) include new questions that have surfaced on Discord, the forum and in community support calls.

**Comment by 10thfloor** [comment]
Are we tracking these anywhere @caseyturnerarrington @psiemens ?

**Comment by caseyturnerarrington** [comment]
@psiemens yeah do we have a list of these I can work off of?

**Comment by caseyturnerarrington** [comment]
@psiemens whats the dealeo with this ticket?

**Comment by psiemens** [comment]
@caseyturnerarrington Oops, meant to move to Sprint 32. Updated the milestone

**Comment by 10thfloor** [comment]
PRed here: https://github.com/onflow/flow/pull/397
