### ISSUE TITLE
Query blockchain data

### ISSUE THREAD

**Issue by brianastrove** [onflow/flow#349]
## Context

Partners are asking how to query blockchain data. We need to update docsite to answer them.

## Definition of Done

Doc published explaining 

- Intro to this document
- The data available on Access Nodes
- How to connect to the access node
- How to query data

## Internal Testing 
Estimation of core issue should capture larger testing efforts

**Comment by brianastrove** [comment]
Intro draft below and [link to collaborate](https://docs.google.com/document/d/1QWP4zmQMV9SnkIxi7n7NUE71RLZsHJaQsbqZctNoq3k/edit?usp=sharing):

Querying blockchain data on Flow is easy. There is a node type called the Access Node that stores the data for consumption. The data available is…This is how you connect to the access node and query data…

**Comment by kerrywei** [comment]
This issue can be closed now given the proposed contents are flushed to Flow doc site at https://docs.onflow.org/faq/developers/#how-can-i-connect-to-and-query-the-access-nodes-what-data-is-available-there
