### ISSUE TITLE
How apps capture events

### ISSUE THREAD

**Issue by brianastrove** [onflow/flow#350]
## Context

Partners asking how apps capture events and what events used for on flow and in Cadence

## Definition of Done

Doc published explaining
* Intro to events
* How events used on flow and in cadence
* What types of events exists
* How apps capture events
* How to emit events

**Comment by brianastrove** [comment]
Intro draft here and google[ doc to collaborate](https://docs.google.com/document/d/1iDlZmaCxf_94Ei_HAoyjgT8P1cmB-mRg8TTmF-2hR2E/edit?usp=sharing):

You're probably here to understand how apps can capture events emitted on flow. You've come to the right place. This is how...

**Comment by studio1vc** [comment]
@brianastrove cleaning up the backlog. Is this work still outstanding and if so planned for next sprint? (starting Monday)

**Comment by psiemens** [comment]
Moving to Mar 29 sprint

**Comment by kerrywei** [comment]
closing this issue as the contents have been flushed to Flow doc site at https://docs.onflow.org/faq/developers/#how-do-apps-consume-events-how-do-events-work
