### ISSUE TITLE
Access API protobuf definitions are not namespaced

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#36]
### Problem

The protobuf definitions for the Access API are not namespaced inside of `flow`, which can create conflicts in the generated code for some languages.

For example, as reported by a user:

> `access.proto` generates a C++ namespace `access` that clashes with the `unistd.h` library ("symbol already in use").  This problem (not observable in the golang implementation) could be avoided if the package name corresponded to the directory hierarchy (`flow.access`).

### Context

While adding the namespace itself is trivial, it introduces a breaking change for all services, methods and messages (old versions of the API register all types without the namespace). Fixing this bug introduces non-trivial complications for clients and servers.

**Comment by turbolent** [comment]
Is it enough to add `package` statements to the protobuf files?

**Comment by psiemens** [comment]
Protobuf has a `go_package` option for Go, but unfortunately there's no equivalent for C++, which generates namespaces based on the package name declared by `package`.

Ref: https://github.com/onflow/flow/pull/37/files

**Comment by turbolent** [comment]
The docs mention that the normal `package` statement is used:

From https://developers.google.com/protocol-buffers/docs/cpptutorial#defining-your-protocol-format:

> The .proto file starts with a package declaration, which helps to prevent naming conflicts between different projects. In C++, your generated classes will be placed in a namespace matching the package name.

**Comment by turbolent** [comment]
Ah, I understand, we were already using the package option, but the name of the namespace clashes. I should have read the description properly, sorry

**Comment by psiemens** [comment]
@turbolent Yeah, the problem is that the package names are currently `access` and `entities` without any reference to Flow. `access` clashes with the C++ stdlib, so I updated it to `flow.access`, but this unfortunately is not backwards compatible with the old files. Basically, the gRPC server doesn't know that `access` and `flow.access` are the same package so it rejects clients that use the un-namespaced version.

**Comment by psiemens** [comment]
No worries!
