### ISSUE TITLE
Top navigation bar overlaps with right-side contents text

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#366]
### Problem

The top navigation bar overlaps slightly with the right-side contents text when scrolling down the page:

<img width="720" alt="Screen Shot 2021-02-12 at 5 03 41 PM" src="https://user-images.githubusercontent.com/2547035/107837204-bec20980-6d54-11eb-9187-be2316739ce0.png">

### Steps to Reproduce 

Open this page and scroll down: https://docs.onflow.org/cadence

### Acceptance Criteria

The right-side contents should freeze when the navigation bar touches the horizontal rule.

**Comment by 10thfloor** [comment]
I was not able to reproduce this. The overlap appears to be fixed.
![Screen Shot 2021-03-02 at 12 24 34 PM](https://user-images.githubusercontent.com/901466/109710219-40d27080-7b52-11eb-81e2-55b7646a5739.png)
