### ISSUE TITLE
Navigation icons hover state is not clickable

### ISSUE THREAD

**Issue by psiemens** [onflow/flow#368]
### Problem

The navigation icons (Playground, Go SDK, Cadence, etc.) fade on hover, which implies that they are clickable, but in fact they are not.

The icons also fade when hovering over the link text, but this is expected behaviour.

![Feb-13-2021 20-27-54](https://user-images.githubusercontent.com/2547035/107868580-4e8db380-6e3a-11eb-92d0-929a452bb1f0.gif)

### Acceptance Criteria

The icon and link text should be grouped together as a single button with the same hover and click functionality.

**Comment by 10thfloor** [comment]
Fixed in #504
