### ISSUE TITLE
Convert the Transit script to a Cobra script

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/flow#390]
## Context

The Transit script currently is not written using Cobra making it difficult to extent. This issue is to convert the transit script to use Cobra while keep the functionality the same.

## Definition of Done

* Refactor `transit` script to use Cobra
* Each individual command should be a cobra command rather than a flag
  * `transit pull` rather than `transit -pull`

## PR Review 

Who is your Code Partner - algorithm/function check
Who can provide external eyes - sanity check

## Internal Testing 
Estimation of core issue should capture larger testing efforts

**Comment by jordanschalm** [comment]
Note: doing this properly will be a breaking change, since each subcommand will be a proper subcommand rather than a flag

**Comment by vishalchangrani** [comment]
> Note: doing this properly will be a breaking change, since each subcommand will be a proper subcommand rather than a flag

good point. In that case we need to do two things:
1. Keep BisonTrail informed about the change (cc: @ljk662)since they also use the script atleast as a reference.
2. Publish the new version of the script and update the md5sum on this page https://docs.onflow.org/node-operation/node-bootstrap/#download-the-bootstrapping-kit

I can take care of those 2.

**Comment by danuio** [comment]
cc @caseyturnerarrington

**Comment by caseyturnerarrington** [comment]
@vishalchangrani @jordanschalm @danuio how important is this to prioritize? I assume this should be after all Epoch related work. But just wanted to confirm with you three :)

**Comment by vishalchangrani** [comment]
imho - yes, this should come after the Epoch related stuff.

**Comment by jordanschalm** [comment]
Yes, this should come after core epoch tasks. 

However, since we will already be making a set of changes to the operator documentation as part of rolling out epochs, it would be great to do this and include the documentation updates associated with this change at the same time. So we aren't making process changes for node operators more than once.

**Comment by caseyturnerarrington** [comment]
Yup. So this should be done with ticket #5287, right?

**Comment by jordanschalm** [comment]
> So this should be done with ticket #5287, right?

Exactly 👍
