### ISSUE TITLE
Flow CLI doc redirect loop

### ISSUE THREAD

**Issue by sideninja** [onflow/flow#398]
## Instructions

There is a redirect loop on the docs website for Flow CLI. If you add a trailing slash then URL works https://docs.onflow.org/flow-cli/

### Steps to Reproduce 

If you click on the Flow CLI link it points to https://docs.onflow.org/flow-cli and there is a redirect loop on that URL to https://docs.onflow.org/flow-cli

**Comment by psiemens** [comment]
I think this is causing the problem: https://github.com/onflow/flow/blob/master/docs/vercel.json#L323-L332

**Comment by psiemens** [comment]
Solved by https://github.com/onflow/flow/commit/dc79df6845a2c2d05b929cbaedb4972a6711db33

Nice @10thfloor 👏
