### ISSUE TITLE
The link in the Voting Contract tutorial takes you to the Kitty Hat playground

### ISSUE THREAD

**Issue by dalton** [onflow/flow#413]
### Problem

When I'm on the [Voting Contract tutorial](https://docs.onflow.org/cadence/tutorial/08-voting/) and I click on the Flow Playground link [https://play.onflow.org/f608ebbd-f8a0-4c6a-9a51-d1c62fc0d3bb](https://play.onflow.org/f608ebbd-f8a0-4c6a-9a51-d1c62fc0d3bb) it takes me to the Kitty Hat playground, not the Voting Contract playground.

### Steps to Reproduce 

Click the link above and you'll see you're on the Kitty Hat playground.

### Acceptance Criteria

When I click the link I should be on the Voting Contract playground.
  
### Context

Running through the tutorials.

**Comment by joshuahannan** [comment]
Thank you for reporting! I put up a PR to fix it.
