### ISSUE TITLE
[Spike] - Investigate concurrent optimistic execution

### ISSUE THREAD

**Issue by caseyturnerarrington** [onflow/flow#439]
- [ ] Explore how much the transactions are parallelizable
  - [ ] Add logging to FVM
  - [ ] See how many conflicts we have 
- [ ] Recommend options based on this

**Comment by ramtinms** [comment]
As the very first step, we probably should add some data collection to figure out what the data contention looks like right now on mainnet transactions.

**Comment by ramtinms** [comment]
To keep all data inside this issue 
@janezpodhostnik recently pointed out fee collection probably can cause a big issue since all tokens goes into a feecollector contract.

**Comment by studio1vc** [comment]
@m4ksio closing this issue and recreated it under the right repo [here](https://app.zenhub.com/workspaces/flow-protocol-5a2ad022cee40e25b0885f82/issues/dapperlabs/flow-go/5479).
