### ISSUE TITLE
Migrate existing documentation

### ISSUE THREAD

**Issue by turbolent** [onflow/flow#46]
Now that the new documentation was moved into this repository, the documentation that already existed in the repository's `docs` directory should be migrated/integrated into the new documentation website, e.g. cli.md, emulator.md, etc.

**Comment by turbolent** [comment]
@10thfloor what is the plan here?

**Comment by 10thfloor** [comment]
Will wait before migrating. There are 2 options: 
- Migrate manually
- Pull from github

Either way, we'll need to understand _where_ the docs will live on the site before I do any work moving content over. 
In general, we don't have a satisfactory information architecture for the docs site, which I think is blocking this task.

**Comment by turbolent** [comment]
@10thfloor there are sill old docs in the repo. I think they can be removed now:
- https://github.com/onflow/flow/blob/master/docs/cli.md
- https://github.com/onflow/flow/blob/master/docs/emulator.mdx

**Comment by kerrywei** [comment]
Hey @turbolent , I'm closing this issue given the doc site migration is done, and these two links provided in the comment are no longer available. If I miss something here, please definitely re-open and point me to things that need to be addressed as part of this issue. Thank you
