### ISSUE TITLE
Account keys weight documentation

### ISSUE THREAD

**Issue by sideninja** [onflow/flow#473]
### Problem

Account [keys weight documentation](https://docs.onflow.org/concepts/accounts-and-keys/) is a bit confusing. 

It says that an account key weight is an integer between 1-1000:
> Weight (integer between 1-1000)

But then in the signing examples, it uses 0 - 1 range for weights. 
> ACCOUNT | KEY ID | WEIGHT
> -- | -- | --
> 0x01 | 1 | 1.0

Should that be changed to a number between 1 - 1000.

**Comment by 10thfloor** [comment]
Should be "Between 0 and 1"

**Comment by bluesign** [comment]
I think should be: 

`Weight (integer between 0-1000)
`
and 

ACCOUNT | KEY ID | WEIGHT
-- | -- | --
0x01 | 1 | 1000

**Comment by kerrywei** [comment]
another related PR: https://github.com/onflow/flow-go-sdk/pull/239
