### ISSUE TITLE
Typo in Flow docs pages

### ISSUE THREAD

**Issue by farbodg** [onflow/flow#483]
## Context

I found a typo in the title of these pages:
https://docs.onflow.org/flow-cli/account-add-contract
https://docs.onflow.org/flow-cli/account-update-contract/
https://docs.onflow.org/flow-cli/account-remove-contract/
https://docs.onflow.org/flow-cli/account-staking-info/

## Definition of Done

Typos fixed! 😄

**Comment by turbolent** [comment]
Opened a PR: https://github.com/onflow/flow-cli/pull/215
