### ISSUE TITLE
Link not accurate in docs.onflow.org/staking - pls fix

### ISSUE THREAD

**Issue by comtechnet** [onflow/flow#498]
## Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

Search of the following txt in the file ...

If you created your account using the Flow Port, you can also stake and earn rewards using the Flow Port. Follow this step-by-step guide to stake using the Flow Port. Flow Port currently supports staking, delegation and reward withdrawal using Blocto and Ledger accounts / wallets.

The step-by-step guide link in now current/accurate - pls fix

### Steps to Reproduce 

bring up the url docs.onflow.org/staking and find the link - u'll know its wrong

### Acceptance Criteria

fix the link
  
### Context

learning Flow

**Comment by 10thfloor** [comment]
The link seems fine. Could you add some detail about why you think it's not accurate?

**Comment by comtechnet** [comment]
the "step-by-step" internal link was wrong - it now works - thanks
