### ISSUE TITLE
List the addresses for the Flow Token, NFT and FT in the emulator docs

### ISSUE THREAD

**Issue by cybercent** [onflow/flow#54]
## Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Issue To Be Solved
List the addresses for the Flow Token, NFT and FT in the emulator docs:
https://github.com/onflow/flow/blob/master/docs/content/emulator/index.md

**Comment by 10thfloor** [comment]
Stale. This information is added here https://docs.onflow.org/core-contracts
