### ISSUE TITLE
Sometimes get error when calling GetTransactionResult

### ISSUE THREAD

**Issue by kwunyeung** [onflow/flow#55]
### Problem

Sometimes get error when calling `GetTransactionResult` of `Access API` and no transaction result is returned.

### Steps to Reproduce 

Get the transaction result of the transaction `bcFyY1Udl9KasyOtT01LIru0T63OosLw4N5ViluHkf4=` and will get the following error with `flow-sdk-js`.

```
Error: failed to find: rpc error: code = Internal desc = failed to retrieve result from execution node: rpc error: code = Unimplemented desc = unknown service flow.execution.ExecutionAPI
```

### Acceptance Criteria

<if any>
  
### Context

<what are you currently working on that this is blocking?>

**Comment by caseyturnerarrington** [comment]
Hi @kwunyeung, are you still experiencing this issue?

**Comment by kwunyeung** [comment]
@caseyturnerarrington no. It's good to close this now.
