### ISSUE TITLE
Partner Update Date Change

### ISSUE THREAD

**Issue by kzucky** [onflow/flow#57]
### Problem

Spork is set for October 8th, we need to move it to October 13th

### Steps to Reproduce 

Update the "Coming Up" timeline to October 13: Spork - Candidate #10 (vs Oct 8th right now)

![image](https://user-images.githubusercontent.com/47838402/94479305-74673400-0189-11eb-8989-7ca0fc3d999a.png)

https://docs.onflow.org/intro/partner-update/

### Acceptance Criteria

N/A
  
### Context

Would like to fit in the Replay Mechanism Maks has been working on into the next Spork as well as a set of new node operators who will be set up in time in advance.

cc @Kay-Zee for 👀

**Comment by laynelafrance** [comment]
This was done and is now replaced by #88
