### ISSUE TITLE
Migrate current Reponsible discls

### ISSUE THREAD

**Issue by jkan2** [onflow/flow#578]
## Instructions

Please migrate the current [Responsible Disclosure](https://docs.onflow.org/bounties/responsible-disclosure/) to Flow's parent domain (onflow.org)

### Issue To Be Solved
1. A more suitable location for the responsible disclosure to live in
2. Enable SEO so that Security Researchers/Reporters can easily google the page without having to search for the page in the website 
  
cc @10thfloor

**Comment by 10thfloor** [comment]
Content was migrated.
