### ISSUE TITLE
Flow Docs Updates

### ISSUE THREAD

**Issue by kzucky** [onflow/flow#59]
### Problem

Update needed on Verification Storage recommendations and Execution 

### Steps to Reproduce 

1. Change candidate 8 under Step 0 to candidate 9
![image](https://user-images.githubusercontent.com/47838402/94487344-b4ccaf00-0195-11eb-8faa-c6112b179243.png)

2. Upload your Public Keys

Can we adjust the wording to say, _"(you can pick any name, but please make sure to do so as it helps us immensely to keep track of the most recent keys you've sent and would like us to include in the bootstrapping process)"_
![image](https://user-images.githubusercontent.com/47838402/94487518-ff4e2b80-0195-11eb-8d9c-caea9ff504b3.png)

3. Start your Flow Node
![image](https://user-images.githubusercontent.com/47838402/94487645-2dcc0680-0196-11eb-8f94-afd12bd7c105.png)
Add end parenthesis _"(via Discord you will need to fetch the genesis info), updated..."_

- verification nodes and they have gone slightly over 2GB. So, if our docs still stay 2GB for verification, we should revise it to 4GB at least → this requirement needs to be changed:
-> https://onflow.readme.io/docs/setting-up-a-node#hardware-requirements

- we are also missing instructions w.r.t execution node. The `PULL` token for the execution node is different than other nodes and operators running an execution node should be pulling using that token ->  it is candidate-9-execution
cc @vishalchangrani for 👀

### Acceptance Criteria

NA
  
### Context

<what are you currently working on that this is blocking?>

**Comment by 10thfloor** [comment]
@caseyturnerarrington Stale?

**Comment by caseyturnerarrington** [comment]
Yeah I don't think this is valid anymore. Closing.

**Comment by caseyturnerarrington** [comment]
(I actually can't close. @10thfloor can you close please?)
