### ISSUE TITLE
SEO Issues with the docs 

### ISSUE THREAD

**Issue by sideninja** [onflow/flow#593]
There are some issues with SEO on the docs website.

List of issues I've found:
- Not defined/correctly defined meta tags - meta tags on all docs pages are set to *Start Building in the Open*. Each page should have a better meta description. **This one is important**.
- No language is defined in meta tags, Bing still uses those tags when crawling
- There is no sitemap and no robots.txt
- Alt texts are missing

**Comment by 10thfloor** [comment]
SEO looks pretty good from the google side?
![Screen Shot 2021-08-17 at 2 42 22 PM](https://user-images.githubusercontent.com/901466/129804482-a978d634-480f-49c0-93af-6bfab15b209f.png)
