### ISSUE TITLE
Update Blocto wallet creation instructions

### ISSUE THREAD

**Issue by Kay-Zee** [onflow/flow#617]
## Context

Currently, the blocto wallet creation instructions on the doc site is out of date

https://docs.onflow.org/flow-token/delivery/#blocto

Following these instructions is not sufficient to receive a wallet that is ready for Token Delivery from DapperLabs (e.g. has a properly setup Locked Tokens side car account)

There are additional steps that must be followed.

Ideally, we'd get this in ASAP as many people are currently creating accounts for Token Delivery over the next month or so

**Comment by hanaito0** [comment]
This should be added to after one sets up a Blocto wallet successfully as additional steps to ensure the Blocto wallet is capable of receiving locked FLOW. 

1.  Download the Blocto app
2. Open browser in Blocto app
3. Go to: https://flow-wallet.blocto.app/lock-account
4. Follow the instructions and set up lock account 
OR
Or alternatively, on your mobile device use this link https://blocto.app.link/locked-flow. This will take users through download and open that lock account page

**Comment by 10thfloor** [comment]
OK, I added these instructions: 
https://github.com/onflow/flow/pull/624
@hanaito0 @Kay-Zee
