### ISSUE TITLE
Cadence Tutorials - Update FT and NFT

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow#627]
Update the basic tutorials to include new things:

* latest cadence features
* explain capabilities a bit better
* potentially use standard-compatible code
* maybe re-order FT and NFT tutorials to start with the simplest version and build from there?

**Comment by 10thfloor** [comment]
@joshuahannan Is this in-progress/completed ?

**Comment by joshuahannan** [comment]
This is still in progress. Moving slowly because other things keep pulling my attention away
