### ISSUE TITLE
Request Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [onflow/flow#644]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from the Flow smart contract.

Hoping for some positive inputs/response on this.

**Comment by 10thfloor** [comment]
@sudesh-supraoracles 
I believe Cadence already supports BLS12.
https://docs.onflow.org/cadence/language/crypto/#signature-verification

**Comment by tarakby** [comment]
Sorry for missing this for a long time. BLS signature verification on BSL12-381 is indeed supported by Cadence. 
Closing this issue and feel free to open other issues related to a specific BLS usage.
