### ISSUE TITLE
Change sporks.json structure

### ISSUE THREAD

**Issue by contil** [onflow/flow#700]
lookig at https://github.com/onflow/flow/blob/139cd856b0eed7ee18763329ec155eeded17bf8e/sporks.json#L2 and https://github.com/onflow/flow/blob/139cd856b0eed7ee18763329ec155eeded17bf8e/sporks.json#L381

I propose to change the structure of the file to add a nesting to something like this :

{
  environments: [
     {      
         env-name: "mainnet"
         iteractions: [
             {
                  iter-name: "14"
.....
            }
     } 
     {      
         env-name: "testnet"
             {
                  iter-name: "31"
.....
            }

**Comment by Kay-Zee** [comment]
I'd probably still keep the "spork name" value of `candidate-9` somewhere in the json.

I'm fine with further nesting though, it might be worth mentioning why you feel the additional nesting is superior.

**Comment by contil** [comment]
I think nesting would help while using tools like jq to query and also to group / import new sporks containing only a subdoc for the latest spork ( i.e. imagine to have a subdoc with only mainnet14 and then use jq / shell to create a full env:"mainnet"["1","2".."14"]

the less we leave full access to the full json the less problems we'll probably have with json-linter, indentation ,convert to yaml etc

**Comment by Kay-Zee** [comment]
any issues from your side @franklywatson ?

**Comment by franklywatson** [comment]
No concerns, but would be useful if we can agree on the element names in scope for this change: 

* iteractions - i assume you mean iterations? @contil 
* iter .. means iteration?
* env-name... maybe we want to speak directly to blockchain domain here and use 'network'?

Want to make sure the final version makes things clear. I think ID could be better than iter/iteration, very direct a clear and backed up by the name. Just wondering if there is a better name for 'iterations' to hold the list

**Comment by contil** [comment]
I agree on the terminology ... I borrowed "environment " and "iteration" ( with a typo ) from the TF code but please use the more appropriate terminology that makes sense ....

**Comment by franklywatson** [comment]
👍🏼  So for final confirmation, how about these names and structure:

```
{
  "networks": [
    {
      "name": "mainnet"
      "sporks": [
        {
          "id": "14"
        }
      ]
    },
    {
      "name": "testnet"
      "sporks": [
        {
          "id": "32"
        }
      ]
    }
  ]
}
```

**Comment by franklywatson** [comment]
Hm.. the ID element kind of has an issue when we're referring to mainnet because we have mainnet IDs 4 and up, and the Candidate IDs 4-9. This could result in collisions in the ID for the same network.

**Comment by contil** [comment]
they are at different level and if you drop this it'll be really complicated to query  / sort ( i.e. give me all mainnet data for id[3-10]... I'd actually make the id as integer and keep the name as text ...

**Comment by franklywatson** [comment]
Candidate and Mainnet are not at a different level, they are all mainnet. Look at https://docs.onflow.org/node-operation/past-sporks/ - Candidate 9 precedes Mainnet1, all on the same network. 

Otherwise am not sure what you are saying

**Comment by franklywatson** [comment]
We could use a 0.x indicator ID for the candidates?
