### ISSUE TITLE
Reflect FLIP FEST work in Flow doc site

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow#710]
# Context

There are many new tools built during FLIP FEST. We should highlight the mature ones in our doc site accordingly. 

# Definition of Done

Update the doc site to reflect the following tool

- [Python](https://github.com/janezpodhostnik/flow-py-sdk), [Ruby](https://github.com/glucode/flow_client), Rust (we should list both Rust SDKs as they are very close: https://github.com/MarshallBelles/flow-rust-sdk and https://github.com/fee1-dead/flow.rs), [.Net](https://github.com/tyronbrand/flow.net), [Swift](https://github.com/zed-io/flow-swift) SDKs
- the new [Intellij plugin](https://github.com/cadence-tools/cadence-for-intellij-platform)
- block explorer that supports local emulator: https://github.com/onflowser/flowser
- non-React sample app: Svelte ([https://github.com/amitkothari/crypto-candy/](https://github.com/amitkothari/crypto-candy/)) and Angular JS (https://github.com/ic3guy/FlowAngularExample)

**Comment by kerrywei** [comment]
[Dec 3 update]
In the middle of designing a page to display community tools (i.e. Flowser and many others)

**Comment by sideninja** [comment]
My suggestion would be to treat those SDKs as first-class citizens and give them the same value as to our SDKs, meaning putting them on the same navigation level (along with our SDKs), including their doc in our docs page the same way as our docs, so switching between them gives good UX (reasons behind the uniform format). We can of course have a disclosure that they are community maintained but beside that I would treat them equally, giving the community more incentive to maintain them and making developer discovery easy.

**Comment by kerrywei** [comment]
@kerrywei  to provide a list of things to be shown on flow doc site, @10thfloor will publish them

**Comment by 10thfloor** [comment]
@srinjoyc Question: Do we want all the payout information to go into this doc as well?
