### ISSUE TITLE
Multi-signature Solution

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow#717]
### Issue To Be Solved
**Problem**

Account transactions require a key weight requirements be met. Generally one key will have enough weight to execute a TX but for "multi-sig" transactions a tool is needed to coordinate signatures within the applicable time window. This window is currently estimated at 10 minutes or so.

### Suggested Solution
**Current Solution**

E-mailing/messaging signed messages around. Presumably this is the same method the ancient Romans used during their campaigns in gaul.

**Proposed Solution**

A SPA with realtime message based backend that will coordinate the above. A proposer will create a voucher that will be stored server side and be given a deep link to pass to others to allow them to sign.

**Comment by bluesign** [comment]
I think it would be nice to have this on chain. https://github.com/onflow/service-account/issues/66

**Comment by pgebheim** [comment]
Issue moved to [onflow/flow-multisig #19](https://github.com/onflow/flow-multisig/issues/19) via [**ZenHub**](https://www.zenhub.com/)
