### ISSUE TITLE
Update Playground Tutorial Projects to have the correct README

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow#780]
## Context

The new playground was deployed with a feature to show project names and descriptions.
Need to include this for the tutorials

## Definition of Done

* Find the project links for all the tutorials
* Update the name and descriptions
* Save the new links in the tutorials in the cadence repo, the tutorial code repo, and the playground repo
* Deploy the playground again with the new links

- [x] Hello World
- [x] Fungible Token
- [x] Non Fungible Token
- [x] Marketplace
- [x] Kitty Hats
- [x] Voting

**Comment by 10thfloor** [comment]
cc @kerrywei
