### ISSUE TITLE
Show rate limiting docs

### ISSUE THREAD

**Issue by sideninja** [onflow/flow#840]
There is no documentation about the current rate-limiting of the AN APIs. It's a commonly asked question and hence we should have some guidance around the current rate limits.

**Comment by refi93** [comment]
@vishalchangrani thanks for adding info on the gRPC rate limits, do you know what are the rate limits for the REST API?

**Comment by vishalchangrani** [comment]
> @vishalchangrani thanks for adding info on the gRPC rate limits, do you know what are the rate limits for the REST API?

the limit for the REST API is 10 request per second for each of the api.

**Comment by alxflw** [comment]
@vishalchangrani was the REST API limit part of the PR or are we facing a gap in the docs?
