### ISSUE TITLE
Build-Out Flow API on Flow API Service

### ISSUE THREAD

**Issue by AliSMAmin** [onflow/flow#942]
**Context**

Related to issue [#940](https://github.com/onflow/flow/issues/940). This epic pertains to the Flow API Service, a part of the wider [Flow Access Node Refactoring](https://forum.onflow.org/t/flow-access-architecture-specification/2902).

**Proposed Solution**

The Flow API Service will become its own standalone service hosting the Flow API, renamed from Access API. Internally the Envoy proxy will handle routing to the appropriate component, Blockchain Data Service or DPS, depending on whether a script or a transaction.

**Step Definitions**

•	Flow API Service serves the Flow API
•	Expose the external Flow APIs (gRPC/REST)
•	Flow API responds to requests

**Definition of Done**

•	Flow API successfully queries the downstream Protocol API for protocol state
•	Successfully sends transaction requests from clients to Access or Observer
•	Endpoint are exposed that query the protocol state & forward requests to the downstream Protocol API

**Comment by franklywatson** [comment]
Issue moved to [onflow/flow-go #2485](https://github.com/onflow/flow-go/issues/2485) via [**ZenHub**](https://www.zenhub.com/)

**Comment by szegedim** [comment]
Updated https://github.com/GetElastech/api-service/tree/feature/proxy-0602g
