### ISSUE TITLE
Create Cadence Style Guide

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow#960]
## Context

Developers need better guidelines for how to write clean cadence code.

## Definition of Done

Create a guide in the cadence section of the docs site that give recommendations for Cadence style

* line length
* function, field, and type comments (paremeters returns) `///` (three slashes)
* indentation, spaces
* var/let type, spaces
* bracket spaces
* conditions and panic message formats
* comments on function interface or on function implementation
* Whitespace between code lines
* High level documentation at the beginning of contracts/transactions
* Contract, field, and function names and capitalization

## PR Review 

Who is your Code Partner - @joshuahannan 
Who can provide external eyes - @satyamakgec

**Comment by alilloig** [comment]
· Path naming, camel case or pascal case and how descriptive the path name should be perhaps?

**Comment by alilloig** [comment]
A folder containing a cadence-style-guide.md file inside flow/docs/content will be the right way of doing this, right?

**Comment by alilloig** [comment]
great, then a document talking about guidelines for the tests would be something we will want?

**Comment by joshuahannan** [comment]
Eventually, but that is out of the scope for this

**Comment by alilloig** [comment]
I'm still waiting to IT to answer on something about creating new repos, when the new repo is created I'll close this issue and recreate it in the new repo if everyone is ok with that

**Comment by bluesign** [comment]
@alilloig https://github.com/onflow/cadence-style-guide  ?
