### ISSUE TITLE
Fix Step 2 in Systemd instructions

### ISSUE THREAD

**Issue by kzucky** [onflow/flow#98]
### Problem

- docs have an error in them which is the reason it took so long to get my node up and running last time. It was eventually determined that the command should be
sudo systemctl enable YOUR-FLOW-NODE.service
not:
sudo systemd enable YOUR-FLOW-NODE.service
Step 2 of the systemd instructions.

^ Feedback from Snowfro Node Operator

### Steps to Reproduce 

N/A

### Acceptance Criteria

Adjust and update wording
  
### Context

Node Operator Onboarding Streamlining process

**Comment by caseyturnerarrington** [comment]
@vishalchangrani it doesn't look like this was updated just yet. Can you take a look at this and see if this is something we should be updating in our node-onboarding docs: https://flow-docs-24qk03ze7.vercel.app/operator/node-bootstrap
